INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (6, 1, 6, 96, 'Parterre ovest centralissimo');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (11, 1, 11, 93, 'Curva nord');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (12, 1, 12, 85, 'Curva sud');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (1, 1, 1, 50, 'Tribuna ovest alta esterna');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (2, 1, 2, 97, 'Tribuna ovest alta interna');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (3, 1, 3, 94, 'Parterre ovest esterno');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (4, 1, 4, 100, 'Parterre ovest interno');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (5, 1, 5, 100, 'Parterre ovest centrale');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (7, 1, 7, 100, 'Tribuna est alta esterna');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (8, 1, 8, 100, 'Tribuna est alta interna');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (9, 1, 9, 100, 'Parterre est esterno');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (10, 1, 10, 100, 'Parterre est interno');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (13, 2, 1, 100, 'Tribuna ovest alta esterna');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (14, 2, 2, 100, 'Tribuna ovest alta interna');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (15, 2, 3, 100, 'Parterre ovest esterno');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (16, 2, 4, 100, 'Parterre ovest interno');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (17, 2, 5, 100, 'Parterre ovest centrale');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (18, 2, 6, 100, 'Parterre ovest centralissimo');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (19, 2, 7, 100, 'Tribuna est alta esterna');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (20, 2, 8, 100, 'Tribuna est alta interna');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (21, 2, 9, 100, 'Parterre est esterno');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (22, 2, 10, 100, 'Parterre est interno');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (23, 2, 11, 100, 'Curva nord');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (24, 2, 12, 100, 'Curva sud');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (25, 3, 1, 100, 'Tribuna ovest alta esterna');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (26, 3, 2, 100, 'Tribuna ovest alta interna');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (27, 3, 3, 100, 'Parterre ovest esterno');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (28, 3, 4, 100, 'Parterre ovest interno');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (29, 3, 5, 100, 'Parterre ovest centrale');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (30, 3, 6, 100, 'Parterre ovest centralissimo');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (31, 3, 7, 100, 'Tribuna est alta esterna');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (32, 3, 8, 100, 'Tribuna est alta interna');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (33, 3, 9, 100, 'Parterre est esterno');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (34, 3, 10, 100, 'Parterre est interno');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (35, 3, 11, 100, 'Curva nord');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (36, 3, 12, 100, 'Curva sud');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (37, 4, 1, 100, 'Tribuna ovest alta esterna');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (38, 4, 2, 100, 'Tribuna ovest alta interna');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (39, 4, 3, 100, 'Parterre ovest esterno');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (40, 4, 4, 100, 'Parterre ovest interno');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (41, 4, 5, 100, 'Parterre ovest centrale');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (42, 4, 6, 100, 'Parterre ovest centralissimo');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (43, 4, 7, 100, 'Tribuna est alta esterna');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (44, 4, 8, 100, 'Tribuna est alta interna');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (45, 4, 9, 100, 'Parterre est esterno');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (46, 4, 10, 100, 'Parterre est interno');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (47, 4, 11, 100, 'Curva nord');
INSERT INTO public.ticket_availability (id, match_id, sector_id, available_quantity, sector_name) OVERRIDING SYSTEM VALUE VALUES (48, 4, 12, 100, 'Curva sud');